//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerificaVersaoDlls.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath1 {
            get {
                return ((string)(this["FilePath1"]));
            }
            set {
                this["FilePath1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 1")]
        public string lbl_Cliente1 {
            get {
                return ((string)(this["lbl_Cliente1"]));
            }
            set {
                this["lbl_Cliente1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath2 {
            get {
                return ((string)(this["FilePath2"]));
            }
            set {
                this["FilePath2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath3 {
            get {
                return ((string)(this["FilePath3"]));
            }
            set {
                this["FilePath3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath4 {
            get {
                return ((string)(this["FilePath4"]));
            }
            set {
                this["FilePath4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 2")]
        public string lbl_Cliente2 {
            get {
                return ((string)(this["lbl_Cliente2"]));
            }
            set {
                this["lbl_Cliente2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 3")]
        public string lbl_Cliente3 {
            get {
                return ((string)(this["lbl_Cliente3"]));
            }
            set {
                this["lbl_Cliente3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 4")]
        public string lbl_Cliente4 {
            get {
                return ((string)(this["lbl_Cliente4"]));
            }
            set {
                this["lbl_Cliente4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath5 {
            get {
                return ((string)(this["FilePath5"]));
            }
            set {
                this["FilePath5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath6 {
            get {
                return ((string)(this["FilePath6"]));
            }
            set {
                this["FilePath6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath7 {
            get {
                return ((string)(this["FilePath7"]));
            }
            set {
                this["FilePath7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath8 {
            get {
                return ((string)(this["FilePath8"]));
            }
            set {
                this["FilePath8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath9 {
            get {
                return ((string)(this["FilePath9"]));
            }
            set {
                this["FilePath9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath10 {
            get {
                return ((string)(this["FilePath10"]));
            }
            set {
                this["FilePath10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath11 {
            get {
                return ((string)(this["FilePath11"]));
            }
            set {
                this["FilePath11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath12 {
            get {
                return ((string)(this["FilePath12"]));
            }
            set {
                this["FilePath12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath13 {
            get {
                return ((string)(this["FilePath13"]));
            }
            set {
                this["FilePath13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath14 {
            get {
                return ((string)(this["FilePath14"]));
            }
            set {
                this["FilePath14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath15 {
            get {
                return ((string)(this["FilePath15"]));
            }
            set {
                this["FilePath15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath16 {
            get {
                return ((string)(this["FilePath16"]));
            }
            set {
                this["FilePath16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath17 {
            get {
                return ((string)(this["FilePath17"]));
            }
            set {
                this["FilePath17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath18 {
            get {
                return ((string)(this["FilePath18"]));
            }
            set {
                this["FilePath18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath19 {
            get {
                return ((string)(this["FilePath19"]));
            }
            set {
                this["FilePath19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath20 {
            get {
                return ((string)(this["FilePath20"]));
            }
            set {
                this["FilePath20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 5")]
        public string lbl_Cliente5 {
            get {
                return ((string)(this["lbl_Cliente5"]));
            }
            set {
                this["lbl_Cliente5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 6")]
        public string lbl_Cliente6 {
            get {
                return ((string)(this["lbl_Cliente6"]));
            }
            set {
                this["lbl_Cliente6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 7")]
        public string lbl_Cliente7 {
            get {
                return ((string)(this["lbl_Cliente7"]));
            }
            set {
                this["lbl_Cliente7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 8")]
        public string lbl_Cliente8 {
            get {
                return ((string)(this["lbl_Cliente8"]));
            }
            set {
                this["lbl_Cliente8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 9")]
        public string lbl_Cliente9 {
            get {
                return ((string)(this["lbl_Cliente9"]));
            }
            set {
                this["lbl_Cliente9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 10")]
        public string lbl_Cliente10 {
            get {
                return ((string)(this["lbl_Cliente10"]));
            }
            set {
                this["lbl_Cliente10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 11")]
        public string lbl_Cliente11 {
            get {
                return ((string)(this["lbl_Cliente11"]));
            }
            set {
                this["lbl_Cliente11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 12")]
        public string lbl_Cliente12 {
            get {
                return ((string)(this["lbl_Cliente12"]));
            }
            set {
                this["lbl_Cliente12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 13")]
        public string lbl_Cliente13 {
            get {
                return ((string)(this["lbl_Cliente13"]));
            }
            set {
                this["lbl_Cliente13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 14")]
        public string lbl_Cliente14 {
            get {
                return ((string)(this["lbl_Cliente14"]));
            }
            set {
                this["lbl_Cliente14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 15")]
        public string lbl_Cliente15 {
            get {
                return ((string)(this["lbl_Cliente15"]));
            }
            set {
                this["lbl_Cliente15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 16")]
        public string lbl_Cliente16 {
            get {
                return ((string)(this["lbl_Cliente16"]));
            }
            set {
                this["lbl_Cliente16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 17")]
        public string lbl_Cliente17 {
            get {
                return ((string)(this["lbl_Cliente17"]));
            }
            set {
                this["lbl_Cliente17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 18")]
        public string lbl_Cliente18 {
            get {
                return ((string)(this["lbl_Cliente18"]));
            }
            set {
                this["lbl_Cliente18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 19")]
        public string lbl_Cliente19 {
            get {
                return ((string)(this["lbl_Cliente19"]));
            }
            set {
                this["lbl_Cliente19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliente 20")]
        public string lbl_Cliente20 {
            get {
                return ((string)(this["lbl_Cliente20"]));
            }
            set {
                this["lbl_Cliente20"] = value;
            }
        }
    }
}
